# Configuration for https://goreleaser.com/
project_name: shim

builds:
  - skip: true

release:
  github:
    owner: jonnylangefeld
    name: shim
  draft: false
  prerelease: false
  name_template: "v{{.Version}}"
